# Generated by Django 4.2.6 on 2024-07-18 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('KPIs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPerformance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_performances', to='KPIs.kpi')),
            ],
            options={
                'unique_together': {('kpi', 'date')},
            },
        ),
    ]
