# Generated by Django 4.2.6 on 2024-07-18 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='head',
        ),
    ]
