# Generated by Django 4.2.6 on 2024-07-18 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='Departments.department')),
            ],
        ),
        migrations.CreateModel(
            name='KPITarget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('target_value', models.FloatField()),
                ('month', models.DateField()),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='KPIs.kpi')),
            ],
            options={
                'unique_together': {('kpi', 'month')},
            },
        ),
    ]
